Added example notebooks.
pnkraemer/tornadox pull request #129
Opened 2022-05-29 12:33 UTC by pnkraemer

There is a very plain jupyter notebook with a tutorial now. Please dont be too critical of the content, it is just to get the ball rolling :) 

This PR also includes 
* notebook-to-md syncing via jupytext (has to be set up manually, see jax' contribution guide; let's write down somewhere what how why etc.)
* notebook linting via nbqa (included in tox)

2022-05-29 14:00 UTC, nathanaelbosch requested changes

2022-05-30 06:13 UTC, pnkraemer commented on docs/tutorial_notebooks/getting_started.md
> +Solvers are tuples of an `init_fn` and a `perform_step_fn`, similar to how `optax` handles optimisers, and `blackjax` handles samplers. The `perform_step_fn` has error estimation and calibration bake
Good idea! (I committed this locally, bc. of the syncing with markdown files.)

2022-05-30 06:13 UTC, pnkraemer commented on docs/tutorial_notebooks/getting_started.md
> +print(ek0)
removed.

2022-05-30 06:14 UTC, pnkraemer commented
I included a notebook-execution check into tox and fixed the current issues with the notebook.

2022-05-30 06:20 UTC, pnkraemer commented
Btw: we could even think about versioning _only_ the `*.md` files (which means git-ignoring the notebooks). See [here](https://jupytext.readthedocs.io/en/latest/examples.html#collaborating-on-jupyter-notebooks). The pro would be that there is only a single version to be tracked (and this whole jupytext-syncing-business is more self-explanatory). But this might remove some outputs, so for now I don't think it is really necessary.

2022-05-30 06:24 UTC, nathanaelbosch approved these changes
Looks good!

Regarding tracking only the .md's: It seems reasonable to me to only track the md files and not the notebooks. But I'm not familiar with the tooling, so I'm fine with whatever you think is sensible to do :)

2022-05-30 06:26 UTC, merged